# -*- coding: utf-8 -*-
"""PCADimensions.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/155esKa-Ygu_OJ7DxQrUpB3clCQ1mmNRg
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.datasets import make_blobs
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

X,y=make_blobs(n_samples=500,n_features=5,centers=3,cluster_std=1.5,random_state=42)

X

scaler=StandardScaler()
X_scaled=scaler.fit_transform(X)

X_scaled

pca=PCA(n_components=2)
X_pca=pca.fit_transform(X_scaled)

df_pca=pd.DataFrame(X_pca,columns=['PC1','PC2'])
df_pca['label']=y

sns.scatterplot(data=df_pca, x='PC1', y='PC2', hue='label', palette='Set2')